# Configurações de Monitores
monitor = ,preferred,auto,1

# Inicialização Automática
exec-once = swaybg -i ~/wallpaper/kaka.png
exec-once = waybar
exec-once = hyprctl setcursor breeze-dark 12
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = sleep 2 && systemctl --user restart xdg-desktop-portal-hyprland

# Variáveis de Aplicativos
$terminal = kitty
$menu = wofi --show drun
$arquivos = nemo
$musica = amberol

# Atalhos Básicos
bind = SUPER, Q, exec, $terminal
bind = SUPER, E, exec, $arquivos
bind = SUPER SHIFT, M, exec, $musica
bind = SUPER, C, killactive
bind = SUPER, W, exec, $menu

# Mover e redimensionar janelas
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

# Workspaces
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5

bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5


# Entrada
input {
    kb_layout = us
    kb_variant = intl
    follow_mouse = 1
}


# Aparência geral
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 1
}


# Decoração
decoration {
    rounding = 22

    blur {
        enabled = true
        size = 5
        passes = 1
    }
}


# Animações
animations {
    enabled = true

    bezier = spring, 0.50, 0.38, 0.25, 1.0

    animation = windows, 1, 2, default, popin
    animation = windowsOut, 1, 4, spring, popin 80%
    animation = fade, 1, 4, default
    animation = workspaces, 1, 5, default, slidevert
}


# Transparência
windowrule = opacity 0.8 0.8, match:class kitty
windowrule = opacity 0.65 0.65, match:class firefox
windowrule = opacity 0.55 0.55, match:class spotify
windowrule = opacity 0.5 0.5, match:class dev.zed.Zed
windowrule = opacity 0.8 0.8, match:class io.bassi.Amberol
windowrule = opacity 0.65 0.65, match:class webcord
windowrule = opacity 0.5 0.5, match:class org.kde.dolphin
windowrule = opacity 0.5 0.5, match:class harmonoid


# Áudio
bind = , XF86AudioRaiseVolume, exec, pamixer -i 5
bind = , XF86AudioLowerVolume, exec, pamixer -d 5
bind = , XF86AudioMute, exec, pamixer -t


# OLED Fake Visual Setup
exec-once = wl-gammactl -g 1.18
exec-once = wlsunset -t 6500 -T 6000
